import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import styles from '../styles/Explanation.module.scss'
import ExplanationText from 'src/components/Explanation/ExplanationText'
import { mainDataExplanation } from 'src/data/Explanation/main'
import { textDataExplanation } from 'src/data/Explanation/text'

const Explanation: React.FC = () => {
  const [step, setStep] = useState(0)
  const dataLength = textDataExplanation.length

  const nextText = () => {
    console.log(step)
    if (step < dataLength) {
      setStep(step + 1)
    }
  }
  return (
    <>
      <Head>
        <title>はじめに</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.displayMainarea}>
            <Image
              src={
                step < dataLength
                  ? mainDataExplanation[step].imageUrl
                  : 'https://images.unsplash.com/photo-1537420327992-d6e192287183?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=388&q=80'
              }
              height={500}
              width={500}
              alt=''
            />
            <p>サンプル画像</p>
          </div>
          <div className={styles.displayTextarea} onClick={nextText}>
            {/* 「はじめに」終了後にgameStepを「1」にする */}
            <div className={styles.displayText}>
              {textDataExplanation.map((obj) =>
                step === obj.step ? (
                  <ExplanationText
                    key={obj.step}
                    name={obj.name}
                    first={obj.first}
                    second={obj.second}
                    third={obj.third}
                  />
                ) : (
                  ''
                ),
              )}
              {step === dataLength ? (
                <Link href='/'>
                  <p className={styles.toTopBtn}>トップページに戻る</p>
                </Link>
              ) : (
                ''
              )}
            </div>
          </div>
        </div>
      </main>
    </>
  )
}

export default Explanation
