import Head from 'next/head'
import styles from '../styles/Explanation.module.scss'

const Explanation: React.FC = () => {
  return (
    <>
      <Head>
        <title>はじめに</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.displayMain}>s</div>
          <div className={styles.displayTextarea}>
            <div className={styles.displayText}>
              <p>【GM】</p>
              <p>はじめまして。</p>
              <p>プレイいただきありがとうございます。</p>
              <p>本作をプレイするにあたって、いくつか説明をさせていただきます。</p>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}

export default Explanation
