import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'

export default function Home() {
  const userData = {
    gameStep: 1,
    playerData: {
      attack: 0,
    },
    itemData: {
      potion: 0,
    },
  }
  return (
    <>
      <Head>
        <title>TRPGクエスト</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className={styles.titleArea}>
          <h1>TRPGクエスト</h1>
          <Link href='Explanation'>
            <p className={styles.titleAreaText}>はじめに</p>
          </Link>
          {userData.gameStep > 0 ? (
            <Link href='CharacterCreate'>
              <p className={styles.titleAreaText}>はじめから</p>
            </Link>
          ) : (
            ''
          )}
          {userData.gameStep > 1 ? <p className={styles.titleAreaText}>つづきから</p> : ''}
        </div>
      </main>
    </>
  )
}
