import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'

export default function Home() {
  const testData = {
    step: 0,
    playerData: {
      attack: 0,
    },
    itemData: {
      potion: 0,
    },
  }
  return (
    <>
      <Head>
        <title>TRPGクエスト</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Link href='Explanation'>
          <p>始めて本ゲームをする方はこちらから</p>
        </Link>
        <p>はじめから</p>
        <p>つづきから</p>
      </main>
    </>
  )
}
